# Generated by Django 5.1.2 on 2024-10-15 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='공고제목')),
                ('company_name', models.CharField(max_length=200, verbose_name='회사명')),
                ('detail_url', models.CharField(max_length=400, verbose_name='디테일 페이지 주소')),
                ('end_date', models.CharField(max_length=11, verbose_name='마감일')),
            ],
        ),
    ]
