# Generated by Django 5.1.2 on 2024-10-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruits', '0002_recruit_platform_name_alter_recruit_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='career',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='신입/경력'),
        ),
        migrations.AddField(
            model_name='recruit',
            name='category_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='카테고리'),
        ),
        migrations.AddField(
            model_name='recruit',
            name='region',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='지역'),
        ),
        migrations.AddField(
            model_name='recruit',
            name='stack',
            field=models.TextField(blank=True, null=True, verbose_name='기술 스택'),
        ),
    ]
