# Generated by Django 5.1.2 on 2024-10-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruits', '0003_recruit_career_recruit_category_name_recruit_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruit',
            name='end_date',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='마감일'),
        ),
    ]
