# Generated by Django 5.1.2 on 2024-10-17 06:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruits', '0004_alter_recruit_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='생성일'),
            preserve_default=False,
        ),
    ]
