# Generated by Django 5.1.2 on 2024-10-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruits', '0005_recruit_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruit',
            name='stack',
            field=models.JSONField(blank=True, null=True, verbose_name='기술 스택'),
        ),
    ]
